# Setup
title:               WildSpoof challenge
tagline:             2025
description:         ''
url:                 https://sasv-challenge.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yihanwu
  url:               https://
  email:             yihanwu@ruc.edu.cn

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
